"""Third migration.

Revision ID: 186e6aeec84d
Revises: 7ee6bb9ae0fd
Create Date: 2022-03-15 13:57:58.348296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '186e6aeec84d'
down_revision = '7ee6bb9ae0fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identification', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('cellphone', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('userType', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cellphone'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('identification')
    )
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('identification', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cellphone', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('userType', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('cellphone', name='users_cellphone_key'),
    sa.UniqueConstraint('email', name='users_email_key'),
    sa.UniqueConstraint('identification', name='users_identification_key')
    )
    op.drop_table('users2')
    # ### end Alembic commands ###
