"""Initial migration.

Revision ID: 7ee6bb9ae0fd
Revises: 
Create Date: 2022-03-15 13:46:13.020405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ee6bb9ae0fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identification', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('cellphone', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('userType', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cellphone'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('identification')
    )
    op.drop_table('weather')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather',
    sa.Column('city', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('temp_lo', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('temp_hi', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('prcp', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True)
    )
    op.drop_table('users')
    # ### end Alembic commands ###
