"""i was testing migration.

Revision ID: b4ded640326f
Revises: 186e6aeec84d
Create Date: 2022-03-15 13:58:35.160166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4ded640326f'
down_revision = '186e6aeec84d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identification', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('cellphone', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('userType', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cellphone'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('identification')
    )
    op.drop_table('users2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users2',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('identification', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cellphone', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('userType', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users2_pkey'),
    sa.UniqueConstraint('cellphone', name='users2_cellphone_key'),
    sa.UniqueConstraint('email', name='users2_email_key'),
    sa.UniqueConstraint('identification', name='users2_identification_key')
    )
    op.drop_table('users')
    # ### end Alembic commands ###
